### PR TITLE
Add providers for linux_ppc64le and linux_aarch64.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Dependency of https://github.com/conda-forge/mpb-feedstock/pull/24.

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by bdice** [comment]
@oskooi @ChristopherHogan This PR is ready to review. Please take a look when you have a chance.

**Comment by oskooi** [comment]
Thanks for updating the recipe. This looks fine.  We've had some issues with the MPB and Meep Conda packages for macOS not working recently which this update might address.

@ChristopherHogan, is this good to go?

**Comment by ChristopherHogan** [comment]
Looks good 👍

**Pull request merged**
